version: "3.9"
services:
  postgresql:
    container_name: 'polar_pg'
    hostname: 'polar_pg'
    image: postgres:13.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data"
  redis:
    container_name: 'polar_redis'
    hostname: 'polar_redis'
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
     - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  dbdata:
  redis-data:
